-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 00:39:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IPN-awards
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IPN-awards` ;

-- -----------------------------------------------------
-- Schema IPN-awards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IPN-awards` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
SHOW WARNINGS;
USE `IPN-awards` ;

-- -----------------------------------------------------
-- Table `IPN-awards`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`area` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idarea`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`procedency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`procedency` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`procedency` (
  `idProcedency` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `idarea` INT NOT NULL,
  PRIMARY KEY (`idProcedency`, `idarea`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Procedency_area1_idx` (`idarea` ASC),
  CONSTRAINT `fk_Procedency_area1`
    FOREIGN KEY (`idarea`)
    REFERENCES `IPN-awards`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`award` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`award` (
  `idaward` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `speech` VARCHAR(700) NOT NULL,
  `award_idaward` INT NULL,
  PRIMARY KEY (`idaward`),
  INDEX `fk_Diploma_Diploma1_idx` (`award_idaward` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_Diploma_Diploma1`
    FOREIGN KEY (`award_idaward`)
    REFERENCES `IPN-awards`.`award` (`idaward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`awarded`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`awarded` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`awarded` (
  `rfc` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `first_surname` VARCHAR(50) NULL,
  `second_surname` VARCHAR(50) NULL,
  `email` VARCHAR(255) NOT NULL,
  `seat_number` INT NULL,
  `activation_code` VARCHAR(16) NULL,
  `confirmed` TINYINT ZEROFILL NOT NULL,
  `is_present` TINYINT ZEROFILL NOT NULL,
  `idaward` INT NOT NULL,
  `idProcedency` INT NOT NULL,
  PRIMARY KEY (`rfc`, `idaward`, `idProcedency`),
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC),
  INDEX `fk_awarded_award1_idx` (`idaward` ASC),
  INDEX `fk_awarded_Procedency1_idx` (`idProcedency` ASC),
  CONSTRAINT `fk_awarded_award1`
    FOREIGN KEY (`idaward`)
    REFERENCES `IPN-awards`.`award` (`idaward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_awarded_Procedency1`
    FOREIGN KEY (`idProcedency`)
    REFERENCES `IPN-awards`.`procedency` (`idProcedency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`observation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`observation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`observation` (
  `idObservation` INT NOT NULL AUTO_INCREMENT,
  `commentary` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idObservation`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `rank` INT NOT NULL,
  PRIMARY KEY (`idtype`),
  UNIQUE INDEX `idtype_UNIQUE` (`idtype` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `activation_code` VARCHAR(32) NULL,
  `verified` TINYINT ZEROFILL NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idtype` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idtype`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_type1_idx` (`idtype` ASC),
  CONSTRAINT `fk_user_type1`
    FOREIGN KEY (`idtype`)
    REFERENCES `IPN-awards`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-awards`.`awarded_has_observation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-awards`.`awarded_has_observation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-awards`.`awarded_has_observation` (
  `rfc` VARCHAR(10) NOT NULL,
  `Observation_idObservation` INT NOT NULL,
  `details` VARCHAR(255) NULL,
  PRIMARY KEY (`rfc`, `Observation_idObservation`),
  INDEX `fk_awarded_has_Observation_Observation1_idx` (`Observation_idObservation` ASC),
  INDEX `fk_awarded_has_Observation_awarded1_idx` (`rfc` ASC),
  CONSTRAINT `fk_awarded_has_Observation_awarded1`
    FOREIGN KEY (`rfc`)
    REFERENCES `IPN-awards`.`awarded` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_awarded_has_Observation_Observation1`
    FOREIGN KEY (`Observation_idObservation`)
    REFERENCES `IPN-awards`.`observation` (`idObservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
