-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 00:39:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IPN-Awards
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IPN-Awards` ;

-- -----------------------------------------------------
-- Schema IPN-Awards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IPN-Awards` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
SHOW WARNINGS;
USE `IPN-Awards` ;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`Area` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idArea`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`Procedency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`Procedency` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`Procedency` (
  `idProcedency` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `idArea` INT NOT NULL,
  PRIMARY KEY (`idProcedency`, `idArea`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Procedency_Area1_idx` (`idArea` ASC),
  CONSTRAINT `fk_Procedency_Area1`
    FOREIGN KEY (`idArea`)
    REFERENCES `IPN-Awards`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`Award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`Award` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`Award` (
  `idAward` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `speech` VARCHAR(700) NOT NULL,
  `Award_idAward` INT NULL,
  PRIMARY KEY (`idAward`),
  INDEX `fk_Diploma_Diploma1_idx` (`Award_idAward` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_Diploma_Diploma1`
    FOREIGN KEY (`Award_idAward`)
    REFERENCES `IPN-Awards`.`Award` (`idAward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`Awarded`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`Awarded` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`Awarded` (
  `rfc` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `first_surname` VARCHAR(50) NULL,
  `second_surname` VARCHAR(50) NULL,
  `email` VARCHAR(255) NOT NULL,
  `seat_number` INT NULL,
  `activation_code` VARCHAR(32) NULL,
  `confirmed` TINYINT ZEROFILL NOT NULL,
  `is_present` TINYINT ZEROFILL NOT NULL,
  `idAward` INT NOT NULL,
  `idProcedency` INT NOT NULL,
  PRIMARY KEY (`rfc`, `idAward`, `idProcedency`),
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC),
  INDEX `fk_Awarded_Award1_idx` (`idAward` ASC),
  INDEX `fk_Awarded_Procedency1_idx` (`idProcedency` ASC),
  CONSTRAINT `fk_Awarded_Award1`
    FOREIGN KEY (`idAward`)
    REFERENCES `IPN-Awards`.`Award` (`idAward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Awarded_Procedency1`
    FOREIGN KEY (`idProcedency`)
    REFERENCES `IPN-Awards`.`Procedency` (`idProcedency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`Observation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`Observation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`Observation` (
  `idObservation` INT NOT NULL AUTO_INCREMENT,
  `commentary` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idObservation`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `rank` INT NOT NULL,
  PRIMARY KEY (`idtype`),
  UNIQUE INDEX `idtype_UNIQUE` (`idtype` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `activation_code` VARCHAR(32) NULL,
  `verified` TINYINT ZEROFILL NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idtype` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idtype`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_type1_idx` (`idtype` ASC),
  CONSTRAINT `fk_user_type1`
    FOREIGN KEY (`idtype`)
    REFERENCES `IPN-Awards`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IPN-Awards`.`Awarded_has_Observation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IPN-Awards`.`Awarded_has_Observation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IPN-Awards`.`Awarded_has_Observation` (
  `rfc` VARCHAR(10) NOT NULL,
  `Observation_idObservation` INT NOT NULL,
  `details` VARCHAR(255) NULL,
  PRIMARY KEY (`rfc`, `Observation_idObservation`),
  INDEX `fk_Awarded_has_Observation_Observation1_idx` (`Observation_idObservation` ASC),
  INDEX `fk_Awarded_has_Observation_Awarded1_idx` (`rfc` ASC),
  CONSTRAINT `fk_Awarded_has_Observation_Awarded1`
    FOREIGN KEY (`rfc`)
    REFERENCES `IPN-Awards`.`Awarded` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Awarded_has_Observation_Observation1`
    FOREIGN KEY (`Observation_idObservation`)
    REFERENCES `IPN-Awards`.`Observation` (`idObservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
