/**
 * Insert # procedency #
 */
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 1 "Gonzálo Vázquez Vela"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 2 "Miguel Bernard"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 3 "Estanislao Ramírez Ruíz"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 4 "Lázaro Cárdenas"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 5 "Benito Juárez"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 6 "Miguel Othón de Mendizabal"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 7 "Cuauhtémoc"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 8 "Narciso Bassols"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 9 "Juan de Dios Bátiz"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 10 "Carlos Vallejo Márquez"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 11 "Wilfrido Massieu"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 12 "José María Morelos"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 13 "Ricardo Flores Magón"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 14 "Luis Enrique Erro"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 15 "Diódoro Antúnez Echegaray"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cecyt 17 "León, Guanajuato"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Cet 1"Walter Cross Buchanan"', (SELECT idarea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Biotecnología Genómica', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Cómputo y Comunicaciones', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Educación Contínua Culiacán', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Educación Contínua Durango', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Educación Contínua Los Mochis', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Educación Contínua Tijuana', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Nanociencias y Micro y Nanotecnologías', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIC', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CICATA, Unidad Altamira', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CICATA, Unidad Legaria', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
-- Centro de Investigación en Ciencia Aplicada y Tecnología Avanzada (CICATA), Unidad Legaria
INSERT INTO procedency (name, idarea) VALUES ('CICATA, Unidad Querétaro', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CICIMAR', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CICS MILPA ALTA', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CICS SANTO TOMÁS', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
-- CICS, Unidad Santo Tomás
INSERT INTO procedency (name, idarea) VALUES ('CIDETEC', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIDIIR, Unidad Durango', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIDIIR, Unidad Oaxaca', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIITEC', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIECAS', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ENCB', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CITEDI', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ENMYH', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESCA SANTO TOMÁS', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESCA TEPEPAN', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESEO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESCOM', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIA TECAMACHALCO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESE', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESFM', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIA TICOMÁN', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIA ZACATENCO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIME AZCAPOTZALCO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIME TICOMÁN', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIME CULHUACÁN', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIME ZACATENCO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIQIE', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESIT', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('EST', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('ESM', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('UPIBI', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('UPII CAMPUS GUANAJUATO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('UPII CAMPUS ZACATECAS', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('UPIICSA', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Investigación y Desarrollo en Tecnología Digital, CITEDI TIJUANA', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('UPIITA', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CEPROBI', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Investigación e Innovación Tecnológica', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIIDIR Michoacán', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CENTRO DE EDUCACIÓN CONTINUA, ING. EUGENIO MÉNDEZ DOCURRO', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('CIIEMAD', (SELECT idarea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idarea) VALUES ('Secretaría Particular de la Dirección General', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Desarrollo Infantil "Clementina Batalla de Bassols"', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Desarrollo Infantil "Amalia Solórzano de Cárdenas"', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Desarrollo Infantil "Margarita Salazar de Erro"', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Centro de Desarrollo Infantil "Laura Pérez de Bátiz"', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación de Asesores', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación de Comunicación Social', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación de Centros de Desarrollo Infantil', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación General de Formación e Innovación Educativa', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación Politécnica para la Sustentabilidad', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación General de Servicios Informáticos', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Defensoría de los Derechos Politécnicos', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Administración Escolar', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Asuntos Jurídicos', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Desarrollo y Fomento Deportivo', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Bibliotecas', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Difusión y Fomento a la Cultura', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Evaluación', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Educación Media Superior', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Normatividad Consulta y Dictaminación', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Capital Humano', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Publicaciones', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Recursos Materiales y Servicios', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Secretaría de Servicios Educativos', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Recursos Financieros', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Secretaría Académica', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Secretaría General', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Oficina del Abogado General', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Unidad Politécnica para el Desarrollo y la Competitividad Empresarial', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Coordinación del Sistema Institucional de Información', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección General', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Educación Superior', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Dirección de Servicios Estudiantiles', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idarea) VALUES ('Unidad Politécnica para la Educación Virtual', (SELECT idarea FROM area WHERE name LIKE ('AREA CENTRAL')));
