/**
 * Insert # Procedency #
 */
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 1 "Gonzálo Vázquez Vela"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 2 "Miguel Bernard"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 3 "Estanislao Ramírez Ruíz"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 4 "Lázaro Cárdenas"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 5 "Benito Juárez"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 6 "Miguel Othón de Mendizabal"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 7 "Cuauhtémoc"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 8 "Narciso Bassols"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 9 "Juan de Dios Bátiz"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 10 "Carlos Vallejo Márquez"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 11 "Wilfrido Massieu"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 12 "José María Morelos"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 13 "Ricardo Flores Magón"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 14 "Luis Enrique Erro"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 15 "Diódoro Antúnez Echegaray"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cecyt 17 "León, Guanajuato"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Cet 1"Walter Cross Buchanan"', (SELECT idArea FROM area WHERE name LIKE ('NIVEL MEDIO SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Biotecnología Genómica', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Cómputo y Comunicaciones', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Educación Contínua Culiacán', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Educación Contínua Durango', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Educación Contínua Los Mochis', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Educación Contínua Tijuana', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Nanociencias y Micro y Nanotecnologías', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIC', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CICATA, Unidad Altamira', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CICATA, Unidad Legaria', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
-- Centro de Investigación en Ciencia Aplicada y Tecnología Avanzada (CICATA), Unidad Legaria
INSERT INTO procedency (name, idArea) VALUES ('CICATA, Unidad Querétaro', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CICIMAR', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CICS MILPA ALTA', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CICS SANTO TOMÁS', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
-- CICS, Unidad Santo Tomás
INSERT INTO procedency (name, idArea) VALUES ('CIDETEC', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIDIIR, Unidad Durango', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIDIIR, Unidad Oaxaca', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIITEC', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIECAS', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ENCB', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CITEDI', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ENMYH', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESCA SANTO TOMÁS', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESCA TEPEPAN', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESEO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESCOM', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIA TECAMACHALCO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESE', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESFM', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIA TICOMÁN', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIA ZACATENCO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIME AZCAPOTZALCO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIME TICOMÁN', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIME CULHUACÁN', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIME ZACATENCO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIQIE', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESIT', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('EST', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('ESM', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('UPIBI', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('UPII CAMPUS GUANAJUATO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('UPII CAMPUS ZACATECAS', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('UPIICSA', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Investigación y Desarrollo en Tecnología Digital, CITEDI TIJUANA', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('UPIITA', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CEPROBI', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Investigación e Innovación Tecnológica', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIIDIR Michoacán', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CENTRO DE EDUCACIÓN CONTINUA, ING. EUGENIO MÉNDEZ DOCURRO', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('CIIEMAD', (SELECT idArea FROM area WHERE name LIKE ('NIVEL SUPERIOR')));
INSERT INTO procedency (name, idArea) VALUES ('Secretaría Particular de la Dirección General', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Desarrollo Infantil "Clementina Batalla de Bassols"', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Desarrollo Infantil "Amalia Solórzano de Cárdenas"', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Desarrollo Infantil "Margarita Salazar de Erro"', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Centro de Desarrollo Infantil "Laura Pérez de Bátiz"', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación de Asesores', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación de Comunicación Social', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación de Centros de Desarrollo Infantil', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación General de Formación e Innovación Educativa', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación Politécnica para la Sustentabilidad', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación General de Servicios Informáticos', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Defensoría de los Derechos Politécnicos', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Administración Escolar', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Asuntos Jurídicos', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Desarrollo y Fomento Deportivo', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Bibliotecas', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Difusión y Fomento a la Cultura', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Evaluación', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Educación Media Superior', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Normatividad Consulta y Dictaminación', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Capital Humano', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Publicaciones', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Recursos Materiales y Servicios', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Secretaría de Servicios Educativos', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Recursos Financieros', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Secretaría Académica', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Secretaría General', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Oficina del Abogado General', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Unidad Politécnica para el Desarrollo y la Competitividad Empresarial', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Coordinación del Sistema Institucional de Información', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección General', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Educación Superior', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Dirección de Servicios Estudiantiles', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
INSERT INTO procedency (name, idArea) VALUES ('Unidad Politécnica para la Educación Virtual', (SELECT idArea FROM area WHERE name LIKE ('AREA CENTRAL')));
